swagger: '2.0'
info:
  version: '1.0.0'
  title: 'Youth Speak Hawaii'
  description: 'This is voluntary association. Currently there are 20 Events, 13 Contacts and 4 Activities. The convention used for numbering starts from 1.'
  contact:
    email: "leosmile38@gmail.com"
  license:
    name: "Apache-2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "youthspeakshawaii.herokuapp.com"
#host: "localhost:3000"
basePath: "/v2"

schemes:
  - "https"
  - "http"

tags:
  - name: "event"
    description: "Events scheduled"
  - name: "activity"
    description: "Activities offered"
  - name: "contact"
    description: "Volunteers"


paths:
  /events:
    get:
      tags:
        - "event"
      summary: "Events scheduled"
      description: "List of events scheduled"
      operationId: "eventsGET"
      produces:
        - "application/json"
      responses:
        '200':
          description: "Collection of events"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Event"
      x-swagger-router-controller: "Event"

  /events/{id}:
    get:
      tags:
        - "event"
      summary: "Find event with the event id"
      operationId: "eventIdGET"
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "id of the event you are searching"
          required: true
          type: "integer"
          format: "int64"
      responses:
        '200':
          description: "operation was successful"
          schema:
            $ref: '#/definitions/Event'
        '400':
          description: Invalid ID supplied
        '404':
          description: Event not found
      x-swagger-router-controller: "Event"

  /events/{id}/contact:
    get:
      tags:
        - "event"
      summary: "Get the contact of an event"
      operationId: "eventsIdContactGET"
      parameters:
        - name: "id"
          in: "path"
          description: "id of the event you want the contact of"
          required: true
          type: "integer"
          format: "int64"
      responses:
        '200':
          description: "successful operation"
          schema:
            $ref: '#/definitions/Contact'
      x-swagger-router-controller: "Event"

  /events/{id}/activity:
    get:
      tags:
        - "event"
      summary: "Get the activity of an event"
      operationId: "eventsIdActivityGET"
      parameters:
        - name: "id"
          in: "path"
          description: "id of the event you want the activity of"
          required: true
          type: "integer"
          format: "int64"
      responses:
        '200':
          description: "successful operation"
          schema:
            $ref: '#/definitions/Activity'

      x-swagger-router-controller: "Event"

  /activities:
    get:
      tags:
        - "activity"
      summary: "Activities related to an event"
      description: "List of all the activities"
      operationId: "activitiesGET"
      produces:
        - "application/json"
      responses:
        '200':
          description: "Collection of activities"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Activity"
      x-swagger-router-controller: "Activity"

  /activities/{id}:
    get:
      tags:
        - "activity"
      summary: "Find activity with the activity id"
      operationId: "activityIdGET"
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "id of the activity you are searching"
          required: true
          type: "integer"
          format: "int64"
      responses:
        '200':
          description: "operation was successful"
          schema:
            $ref: '#/definitions/Activity'
      x-swagger-router-controller: "Activity"
  /activities/{id}/event:
    get:
      tags:
        - "activity"
      summary: "Get the event of an activity"
      operationId: "activitiesIdEventGET"
      parameters:
        - name: "id"
          in: "path"
          description: "id of the activity you want the event of"
          required: true
          type: "integer"
          format: "int64"
      responses:
        '200':
          description: "successful operation"
          schema:
            $ref: '#/definitions/Event'
      x-swagger-router-controller: "Activity"
  /activities/{id}/contact:
    get:
      tags:
        - "activity"
      summary: "Get the contact of an activity"
      operationId: "activitiesIdContactGET"
      parameters:
        - name: "id"
          in: "path"
          description: "id of the activity you want the contact of"
          required: true
          type: "integer"
          format: "int64"
      responses:
        '200':
          description: "successful operation"
          schema:
            $ref: '#/definitions/Contact'
      x-swagger-router-controller: "Activity"

  /contacts:
    get:
      tags:
        - "contact"
      summary: "Finds contacts"
      description: "Get contact"
      operationId: "contactsGET"
      produces:
        - "application/json"
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/Contact'
      x-swagger-router-controller: "Contact"

  /contacts/{id}:
    get:
      tags:
        - "contact"
      summary: "Find contacts by ID"
      operationId: "contactIdGET"
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "id to get the contact"
          required: true
          type: "integer"
          format: "int64"
      responses:
        '200':
          description: "successful operation"
          schema:
            $ref: '#/definitions/Contact'
      x-swagger-router-controller: "Contact"

  /contacts/{id}/events:
    get:
      tags:
        - "contact"
      summary: "Get the events of a contact"
      operationId: "contactsIdEventsGET"
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "ID of contact of which to get the events"
          required: true
          type: "integer"
          format: "int64"
      responses:
        '200':
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: '#/definitions/Event'
      x-swagger-router-controller: "Contact"

  /contacts/{id}/activity:
    get:
      tags:
        - "contact"
      summary: "Get the activities of a contact"
      operationId: "contactsIdActivityGET"
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "ID of contact of which to get the activities"
          required: true
          type: "integer"
          format: "int64"
      responses:
        '200':
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: '#/definitions/Activity'
      x-swagger-router-controller: "Contact"


definitions:

  Event:
    type: "object"
    required:
      - "IDevent"
    properties:
      IDevent:
        type: "integer"
        format: "int64"
      title:
        type: "string"
      location:
        type: "string"
      date:
        type: "string"
        format: "date"
      description:
        type: "string"
      start_time:
        type: "string"
        format: "time"
      end_time:
        type: "string"
        format: "time"
      img:
        type: "string"
      practical_info:
        type: "string"
    xml:
      name: "Event"
    title: "Event"
    description: "An event related to an activity"
    example:
      IDevent: 0
      title: "How to create a poem"
      location: "Honolulu"
      date: "2020-07-21"
      description: "Expressing your thoughts"
      start_time: "16:00"
      end_time: "18:00"
      img: "img base64"
      practical info: "In the first part of this event we'll explain the theory behind poetry composition while the second part is hands-on."

  Activity:
    type: "object"
    required:
      - "IDactivity"
      - "title"
    properties:
      IDactivity:
        type: "integer"
        format: "int64"
      title:
        type: "string"
      description:
        type: "string"
      practical_info:
        type: "string"
      img:
        type: "array"
        items:
          type: "string"
    xml:
      name: "Activity"
    title: "Activity"
    description: "An activity related to an event"
    example:
      IDactivity: 0
      title: "Poetry 101"
      description: "Helping children to create short poems"
      practical_info: "The difficulty level of this activity is low, since it is meant for beginners"
      img: "img_1 base64, img_2 base64, img_3 base64"


  Contact:
    type: "object"
    required:
      - "IDperson"
    properties:
      IDperson:
        type: "integer"
        format: "int64"
      full_name:
        type: "string"
      email:
        type: "string"
      phone:
        type: "string"
      bio:
        type: "string"
      img:
        type: "string"
    xml:
      name: "Contact"
    description: "Volunteer"
    example:
      IDperson: 5
      full_name: "Jason Momoa"
      email: "j_momoa@gmail.com"
      phone: "8014562357"
      bio: "Actor and activist"
      img: "img base64"
